# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- Master

pool:
  vmImage: 'macos-latest'
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'Master'
    apksignerKeystorePassword: 'Xdrzseawq1903'
    apksignerKeystoreAlias: 'SMPSE'
    apksignerKeyPassword: 'Xdrzseawq1903'
    apksignerFile: 'Bash'
    zipalignFile: 'home'
steps:
- task: Gradle
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'
Commit 798a6179: Added README.md, .gitignore (ArchLinuxPackages) filesREADME.mdhttps://github.com/dotnet/docs/issues/37905#issuecomment-1821950717package-lock.jsonmy-name-390215
